-- create database mcq2_db;
use mcq2_db;
CREATE TABLE subjects (
    id bigint AUTO_INCREMENT PRIMARY KEY,
    subject_name VARCHAR(50) NOT NULL
);
INSERT INTO subjects (subject_name) VALUES
("GK"),
("Computer"),
("History");
CREATE TABLE questions (
    id bigint AUTO_INCREMENT PRIMARY KEY,
    question TEXT NOT NULL,
    subject_id bigint NOT NULL,
    option1 VARCHAR(255) NOT NULL,
    option2 VARCHAR(255) NOT NULL,
    option3 VARCHAR(255) NOT NULL,
    option4 VARCHAR(255) NOT NULL,
    ans TINYINT NOT NULL, -- Stores the correct answer as a number (1-4)
    FOREIGN KEY (subject_id) REFERENCES subjects(id)
);
INSERT INTO questions (question, subject_id, option1, option2, option3, option4, ans) VALUES
("What is the capital of France?", 1, "Paris", "London", "Rome", "Berlin", 1),
("Which planet is known as the Red Planet?", 1, "Earth", "Mars", "Jupiter", "Venus", 2),
("Who wrote 'Romeo and Juliet'?", 1, "Mark Twain", "Charles Dickens", "William Shakespeare", "Leo Tolstoy", 3),
("What is the largest mammal?", 1, "Elephant", "Blue Whale", "Giraffe", "Polar Bear", 2),
("Which is the smallest continent?", 1, "Australia", "Europe", "Antarctica", "South America", 1),
("Who painted the Mona Lisa?", 1, "Pablo Picasso", "Vincent van Gogh", "Leonardo da Vinci", "Claude Monet", 3),
("What is the hardest natural substance on Earth?", 1, "Gold", "Iron", "Diamond", "Silver", 3),
("What is the boiling point of water?", 1, "90�C", "100�C", "120�C", "80�C", 2),
("Which ocean is the largest?", 1, "Atlantic", "Indian", "Arctic", "Pacific", 4),
("Who discovered penicillin?", 1, "Marie Curie", "Albert Einstein", "Alexander Fleming", "Isaac Newton", 3),
("What is the square root of 64?", 1, "6", "7", "8", "9", 3),
("Which country has the largest population?", 1, "India", "United States", "China", "Russia", 3),
("In which year did World War I begin?", 1, "1914", "1918", "1939", "1945", 1),
("What is the chemical symbol for gold?", 1, "Ag", "Au", "Fe", "Pb", 2),
("Which planet is closest to the Sun?", 1, "Mercury", "Venus", "Earth", "Mars", 1),
("Who invented the telephone?", 1, "Albert Einstein", "Alexander Graham Bell", "Thomas Edison", "Nikola Tesla", 2),
("What is the longest river in the world?", 1, "Amazon", "Nile", "Yangtze", "Mississippi", 2),
("Which element has the atomic number 1?", 1, "Oxygen", "Carbon", "Hydrogen", "Nitrogen", 3),
("Who was the first man to step on the Moon?", 1, "Yuri Gagarin", "Neil Armstrong", "Buzz Aldrin", "Michael Collins", 2),
("How many continents are there?", 1, "5", "6", "7", "8", 3),
("Which gas do plants absorb from the atmosphere?", 1, "Oxygen", "Carbon Dioxide", "Nitrogen", "Methane", 2),
("What is the smallest unit of life?", 1, "Organ", "Tissue", "Cell", "Organism", 3),
("Which is the largest desert in the world?", 1, "Sahara", "Gobi", "Arabian", "Kalahari", 1),
("Who is known as the father of computers?", 1, "Charles Babbage", "Alan Turing", "Bill Gates", "Steve Jobs", 1),
("Which is the fastest land animal?", 1, "Lion", "Cheetah", "Horse", "Eagle", 2),
("What is the capital of Japan?", 1, "Seoul", "Tokyo", "Beijing", "Shanghai", 2),
("What is the largest bone in the human body?", 1, "Femur", "Skull", "Spine", "Rib", 1),
("Which planet is known as the Earth's twin?", 1, "Mars", "Venus", "Jupiter", "Saturn", 2),
("Who developed the theory of relativity?", 1, "Isaac Newton", "Galileo Galilei", "Albert Einstein", "Nikola Tesla", 3),
("Which vitamin is produced when a person is exposed to sunlight?", 1, "Vitamin A", "Vitamin B", "Vitamin C", "Vitamin D", 4),
("What is the primary language spoken in Brazil?", 1, "Spanish", "French", "Portuguese", "English", 3),
("Which country is the largest in the world by area?", 1, "United States", "China", "Russia", "Canada", 3),
("How many colors are there in a rainbow?", 1, "5", "6", "7", "8", 3),
("What is the process by which plants make their food?", 1, "Osmosis", "Respiration", "Photosynthesis", "Transpiration", 3),
("What is the most spoken language in the world?", 1, "English", "Mandarin", "Spanish", "Hindi", 2),
("In which continent is Egypt located?", 1, "Asia", "Africa", "Europe", "South America", 2),
("What is the main ingredient in sushi?", 1, "Chicken", "Pasta", "Rice", "Beef", 3),
("Who was the first President of the United States?", 1, "George Washington", "Thomas Jefferson", "Abraham Lincoln", "John Adams", 1),
("What is the capital of Canada?", 1, "Toronto", "Vancouver", "Ottawa", "Montreal", 3),
("How many bones are there in the human body?", 1, "204", "206", "208", "210", 2),
("Who discovered gravity?", 1, "Albert Einstein", "Isaac Newton", "Galileo Galilei", "Nicolaus Copernicus", 2),
("What is the largest island in the world?", 1, "Greenland", "Australia", "Borneo", "Madagascar", 1),
("Which metal is liquid at room temperature?", 1, "Gold", "Mercury", "Silver", "Iron", 2),
("Which is the largest organ in the human body?", 1, "Heart", "Liver", "Brain", "Skin", 4),
("How many players are there in a soccer team?", 1, "9", "10", "11", "12", 3),
("What is the currency of Japan?", 1, "Won", "Yen", "Yuan", "Ringgit", 2),
("Who painted the ceiling of the Sistine Chapel?", 1, "Leonardo da Vinci", "Michelangelo", "Raphael", "Donatello", 2),
("Which is the tallest mountain in the world?", 1, "K2", "Mount Everest", "Kangchenjunga", "Makalu", 2),
("Who invented the light bulb?", 1, "Albert Einstein", "Nikola Tesla", "Alexander Graham Bell", "Thomas Edison", 4);

INSERT INTO questions (question, subject_id, option1, option2, option3, option4, ans) VALUES
("Who is known as the father of computers?", 2, "Charles Babbage", "Alan Turing", "Bill Gates", "Steve Jobs", 1),
("Which device is used to input data into a computer?", 2, "Monitor", "Mouse", "Keyboard", "Printer", 3),
("What does CPU stand for?", 2, "Central Processing Unit", "Computer Personal Unit", "Control Processing Unit", "Central Print Unit", 1),
("Which of these is an example of an operating system?", 2, "Windows", "Photoshop", "Oracle", "Microsoft Office", 1),
("Which company developed the iPhone?", 2, "Google", "Microsoft", "Apple", "Samsung", 3),
("What does RAM stand for?", 2, "Read Access Memory", "Random Access Memory", "Randomly Accessed Memory", "Run Access Memory", 2),
("Which language is primarily used for web development?", 2, "Java", "Python", "HTML", "C++", 3),
("What is the brain of the computer?", 2, "Motherboard", "CPU", "RAM", "Hard Drive", 2),
("What does USB stand for?", 2, "Universal Serial Bus", "Universal System Bus", "Universal Service Board", "Universal Serial Board", 1),
("Which company is known for making the Windows operating system?", 2, "Apple", "Microsoft", "Google", "IBM", 2),
("What is the main function of the computer's operating system?", 2, "Managing hardware", "Running applications", "Networking", "All of the above", 4),
("Which programming language is used for artificial intelligence?", 2, "Python", "HTML", "CSS", "SQL", 1),
("Which key combination is used to copy text?", 2, "Ctrl + P", "Ctrl + V", "Ctrl + X", "Ctrl + C", 4),
("Which device is used to store data?", 2, "Monitor", "Keyboard", "Hard Drive", "Mouse", 3),
("Who founded Microsoft?", 2, "Steve Jobs", "Elon Musk", "Bill Gates", "Larry Page", 3),
("Which part of a computer is considered its 'memory'?", 2, "CPU", "RAM", "Motherboard", "Hard Drive", 2),
("What does HTTP stand for?", 2, "Hyper Text Transfer Protocol", "Hyper Text Transmission Protocol", "Hyper Text Transfer Platform", "Hyper Text Transfer Procedure", 1),
("Which storage device has the highest speed?", 2, "Hard Disk", "Solid State Drive (SSD)", "DVD", "USB", 2),
("What does GUI stand for?", 2, "General User Interface", "Graphical User Interface", "Graph User Interface", "Graphical Use Interface", 2),
("Which of the following is a search engine?", 2, "Linux", "Google", "Windows", "Yahoo", 2),
("What is the function of a compiler?", 2, "Runs a program", "Deletes files", "Translates code to machine language", "Saves files", 3),
("Which of these is NOT an input device?", 2, "Keyboard", "Mouse", "Printer", "Scanner", 3),
("Which company developed Android OS?", 2, "Apple", "Microsoft", "Google", "IBM", 3),
("What does IP stand for in computer networking?", 2, "Internet Protocol", "Internal Process", "Instant Protocol", "Internet Program", 1),
("Which technology is used to make telephone calls over the internet?", 2, "Fiber optics", "VoIP", "Modem", "Bluetooth", 2),
("What is the full form of Wi-Fi?", 2, "Wireless Fidelity", "Wired Fidelity", "Wireless Fiber", "Wide Fidelity", 1),
("Which file format is used for images?", 2, ".exe", ".jpg", ".docx", ".ppt", 2),
("What is the main page of a website called?", 2, "URL", "Home Page", "Server", "Index", 2),
("What is phishing?", 2, "Email scam", "Virus", "Firewall", "Antivirus software", 1),
("Which of these is a mobile operating system?", 2, "Linux", "Android", "Photoshop", "Windows", 2),
("Which device connects a computer to a network?", 2, "Modem", "Mouse", "Printer", "Keyboard", 1),
("What is BIOS?", 2, "Basic Input Output System", "Binary Internet Operating System", "Best Input Output System", "Basic Internal Output System", 1),
("Which programming language is used for Android development?", 2, "Swift", "Python", "Java", "Ruby", 3),
("What is the function of a firewall?", 2, "Enhances speed", "Protects against viruses", "Manages emails", "Blocks unauthorized access", 4),
("Which is a type of malware?", 2, "Windows", "Virus", "Mac", "Linux", 2),
("What is the binary equivalent of the decimal number 10?", 2, "1010", "1100", "1110", "1001", 1),
("Which device is used to output sound?", 2, "Monitor", "Speaker", "Keyboard", "Printer", 2),
("What does URL stand for?", 2, "Universal Resource Locator", "Uniform Resource Locator", "Uniform Reference Link", "Universal Reference Locator", 2),
("Which company owns the browser Chrome?", 2, "Microsoft", "Apple", "Mozilla", "Google", 4),
("What is the shortcut for pasting text?", 2, "Ctrl + C", "Ctrl + X", "Ctrl + V", "Ctrl + Z", 3),
("What type of file is a .mp3?", 2, "Video file", "Image file", "Audio file", "Text file", 3),
("Which is a command-line operating system?", 2, "Windows", "Linux", "iOS", "Android", 2),
("What is the main function of an IP address?", 2, "Identify a device on a network", "Store data", "Encrypt files", "Run applications", 1),
("Which language is primarily used for iOS development?", 2, "Python", "Swift", "Java", "C#", 2),
("What is the primary function of a router?", 2, "Store data", "Process data", "Direct network traffic", "Create graphics", 3),
("What does SSL stand for?", 2, "Secure Sockets Layer", "Secure System Level", "System Security Layer", "System Socket Level", 1),
("Which component is responsible for graphics?", 2, "CPU", "RAM", "GPU", "Motherboard", 3),
("What does FTP stand for?", 2, "File Transfer Protocol", "File Transmission Platform", "File Tracking Program", "Fast Transfer Process", 1),
("Which of these is an email protocol?", 2, "HTTP", "SMTP", "HTML", "FTP", 2),
("Which device is necessary for the internet connection?", 2, "Keyboard", "Modem", "Printer", "Monitor", 2),
("Which language is primarily used for database queries?", 2, "SQL", "Python", "HTML", "JavaScript", 1);
